### ISSUE TITLE
Unhusk surgeries

### ISSUE THREAD

**Issue by JohnFulpWillard** [vlggms/tegustation#19]
I'm willing to personally watch over to help with this, but I'd like tend wound surgery unhusking to be removed, as well as all the merge conflicting code that went along with it. I'd like to instead see a surgery that is researched with (probably Experimental) surgery research, and will unhusk someone with little (im thinking as low as 10-30 units) of synthflesh, which would also work on changeling husks

**Comment by Kitsunemitsu** [comment]
Tend wounds doesn't unhusk and I can probably just make it a really annoying surgery like debriding flesh

**Comment by Samuuu3** [comment]
How is this an issue?

**Comment by JohnFulpWillard** [comment]
> 
> 
> How is this an issue?

Issues are used both for bug reports, and for feature requests.

**Comment by Samuuu3** [comment]
No like why does this need to be changed?

**Comment by JohnFulpWillard** [comment]
> 
> 
> No like why does this need to be changed?

Because tend wound unhusking was not fun, fair or good. rather than having to make 100 units of synthflesh or go to genetics, you can just to tend wound surgery, a surgery you'd already have to do.

**Comment by Samuuu3** [comment]
I'd like to have actual conversations in our discord before making an issue for a change u want without consulting us
