### ISSUE TITLE
Removal of SalChems

### ISSUE THREAD

**Issue by JohnFulpWillard** [vlggms/tegustation#20]
Another easy thing, removing SalChems. Just deleting the files and anywhere those chems are brought up (Im assuming its just in Mediborg hyposprays)

**Comment by EgorDinamit** [comment]
For a note: SalChems are synthetic bullshit that was only ever used by mediborgs.

**Comment by JohnFulpWillard** [comment]
> For a note: SalChems are synthetic bullshit that was only ever used by mediborgs.

It also had such grudgecode like silver sulfur
