### ISSUE TITLE
Digitigrade shoes do not spawn on digigrade legs nor fit on digitigrade legs

### ISSUE THREAD

**Issue by retlaw34** [vlggms/tegustation#36]
## Round ID: 
[667](https://scrubby.melonmesa.com/round/667)

## Testmerges:
#3 

## Reproduction:
Digitigrade shoes don't seem to be working after the tg merge
1. Join as a lizardperson with digitigrade legs
2. attempt to put on digitigrade shoes

**Comment by EgorDinamit** [comment]
foken /tg/ merges. Gotta fix it the second time...
